
var addNavLinks = function () {
    
    // see if the page is generated by lwarp
    lwarp_meta = document.getElementsByName("generator");
    if (lwarp_meta.length > 0
        && lwarp_meta[0].content == "LaTeX Lwarp package") {
        // add the navigation links
        var backToMainLink = document.createElement('a');
        // see if there's topnavigation
        topNavigation = document.getElementsByClassName("topnavigation")[0];
        if (topNavigation) {
        }
        else {
            topNavigation = document.createElement('nav');
            topNavigation.className = "topnavigation";
            document.body.insertBefore(topNavigation, document.body.firstChild);
        }
        backToMainLink.setAttribute('class', 'topnavlink');
        backToMainLink.href = "/cyrillic/";
        backToMainLink.innerHTML = "回到主站";
        topNavigation.insertBefore(backToMainLink, topNavigation.firstChild);
    }

    // nextLink.setAttribute('href', "node-" + (nodeNum + 1) + ".html");
    // if (nodeNum > 0) {
    //     var div = document.getElementsByClassName("topnavigation")[0];
    //     // empty it
    //     var elem = document.getElementsByClassName("linkhome")[0];
    //     elem.style.display = "none";
    //     // Contents
    //     var navContents = document.createElement('a');
    //     navContents.setAttribute('id', 'topnavcontents');
    //     navContents.setAttribute('class', 'topnavcontents');
    //     navContents.setAttribute('href', 'javascript:void(0);');
    //     navContents.setAttribute('onclick', 'toggleSideNav()');
    //     navContents.setAttribute('title', 'Toggle contents');
    //     navContents.textContent = "Contents";
    //     div.appendChild(navContents);
    //     // Title
    //     var navTitle = document.createElement('span');
    //     navTitle.setAttribute('id', "topnavtitle");
    //     navTitle.textContent = document.title;
    //     div.appendChild(navTitle);
    //     // link to next page
    //     var nextLink = document.createElement('a');
    //     if (nodeNum == maxNodeNum()) {
    //         nextLink.style.display = "none";
    //     }
    //     else {
    //         nextLink.setAttribute('href', "node-" + (nodeNum + 1) + ".html");
    //     }

    //     nextLink.setAttribute('id', "navnext");
    //     nextLink.setAttribute('class', "topnavlink");
    //     nextLink.textContent = "Next";
    //     div.appendChild(nextLink);
    //     // link to homepage
    //     var homeLink = document.createElement('a');
    //     homeLink.setAttribute('href', "index.html");
    //     homeLink.setAttribute('id', "navhome");
    //     homeLink.setAttribute('class', "topnavlink");
    //     homeLink.textContent = "Home";
    //     div.appendChild(homeLink);
    //     // link to previous page
    //     var prevTarget = "index.html";
    //     if (nodeNum > 2) {
    //         prevTarget = "node-" + (nodeNum - 1) + ".html";
    //     }
    //     var prevLink = document.createElement('a');
    //     prevLink.setAttribute('href', prevTarget);
    //     prevLink.setAttribute('id', "navprev");
    //     prevLink.setAttribute('class', "topnavlink");
    //     prevLink.textContent = "Prev";
    //     div.appendChild(prevLink);
    // }
}

window.onload = function () {
    addNavLinks();
}